development:
  adapter: postgresql
  database: listenlog_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: listenlog_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: listenlog_production
  pool: 5
  timeout: 5000
